[package]
name = "libpyepa"
version = "0.1.0"
edition = "2021"

[dependencies]
curve25519-dalek = "4.1.3"
hex = "0.4.3"
hkdf = "0.12.4"
rand_core = { version = "0.9.3", features = ["std"] }
ring = "0.17.14"
secp256k1 = { version = "0.30.0", features = ["rand"] }
thiserror = "2.0.12"
